spring.application.name=revenue-recovery
server.port=8080

# Razorpay Test Credentials
razorpay.key.id=rzp_test_TXeDK9C94CB415
razorpay.key.secret=Pt49BM4z2L2YPWDZf6SRHdCI

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:recoverydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true